### PR TITLE
Notification button  buttun-52

### PR DESCRIPTION
**Pull request by sinanptm**
image

This Pr  Adds new Button to the buttons collection

### CODE REVIEW

**Comment by pasqualevitiello** [comment]
Thanks for your contribution, this is definitely a component that adds value to the set. However, some changes are required:

1. Consider making the badge width flexible to accommodate larger notification counts
2. Improve accessibility by adding aria-label and aria-hidden attributes
3. For consistency, let's align the Lucide icon attributes with our other components
4. For the click behavior, removing the badge might be more intuitive than decrementing it

**Comment by sinanptm** [comment]
Thank you for the detailed feedback and for pointing out the areas of improvement. I appreciate your insights and suggestions to align the component with the project's standards. Here’s my plan to address the changes:

Flexible Badge Width: I’ll update the badge width to handle larger notification counts dynamically.
Accessibility: I’ll add aria-label and aria-hidden attributes to enhance accessibility.
Icon Attribute Consistency: I’ll align the Lucide icon attributes with the standards followed in the other components.
Click Behavior: I’ll modify the click behavior to remove the badge instead of decrementing it for a more intuitive experience.


I’ll make the updates and push the changes shortly.

**Comment by sinanptm** [comment]
@pasqualevitiello  Just updated the component as you said could you please review it.

**Review by pasqualevitiello — CHANGES_REQUESTED** [review]
Please change it to:

```
"use client";

import { Button } from "@/components/ui/button";
import { Bell } from "lucide-react";
import { useState } from "react";

export default function ButtonDemo() {
  const [count, setCount] = useState(3);

  // Reset count on button click
  const handleClick = () => {
    setCount(0);
  };

  return (
    <Button
      variant="outline"
      size="icon"
      className="relative"
      onClick={handleClick}
      aria-label="Notifications"
    >
      <Bell size={16} strokeWidth={2} aria-hidden="true" />
      {count > 0 && (
        <span
          className="absolute left-full -top-2 -translate-x-1/2 inline-flex h-5 min-w-[20px] items-center justify-center rounded-full bg-primary px-1 text-xs font-medium text-primary-foreground"
          aria-hidden="true"
        >
          {count > 99 ? "99+" : count}
        </span>
      )}
    </Button>
  );
}
```

**Comment by sinanptm** [comment]
@pasqualevitiello  done

**Pull request merged**
