### PR TITLE
Add shrink-0 to prevent downsizing icon

### PR DESCRIPTION
**Pull request by doooooooooots**

### CODE REVIEW

**Comment by pasqualevitiello** [comment]
Hey @doooooooooots, thanks for your PRs! I'm not seeing the icon shrinking you mentioned. Could you share a quick screen recording showing the issue?

**Comment by doooooooooots** [comment]
Currently
```<div className="max-w-[150px]"><Button51 /></div>```
Capture d’écran 2024-10-31 à 16 36 13

--- 

Expected
```<div className="max-w-[150px]"><Button51WithShrink0 /></div>```
Capture d’écran 2024-10-31 à 16 36 31

**Comment by pasqualevitiello** [comment]
This is what I see:
Screenshot 2024-10-31 at 16 58 33

**Comment by doooooooooots** [comment]
Oh you're right sorry. Shadcn button has ```[&_svg]:shrink-0``` class.
It seems my button wasn't up to date.
Sorry.

**Comment by pasqualevitiello** [comment]
no worries!

**Pull request closed without merging**
