### PR TITLE
Refactor directional classes for RTL support

### PR DESCRIPTION
**Pull request by iftachhh**
This PR refactors all directional class names (`pr-*`, `pl-*`, `mr-*`, `ml-*`, `left-*`, `right-*`, etc) to contextual equivalents (`pe-*`, `ps-*`, `me-*`, `ms-*`, `start-*`, `end-*`, etc) to better support RTL languages like Hebrew and Arabic. By making these classes directionally agnostic, the layout will adjust dynamically based on text direction, improving flexibility and localization.

**BEFORE (demo page with `dir=rtl`):**

before

**AFTER:**

after

### CODE REVIEW

**Comment by yishayhaz** [comment]
+1
Very useful and should be a standard practice in every UI library!

**Comment by pasqualevitiello** [comment]
Hey @yishayhaz, I've just merged your PR. Thanks a lot for contributing!

**Comment by pasqualevitiello** [comment]
Sure! 🤦 Thanks @iftachhh!

**Comment by nahasco** [comment]
Why force input 46 (Phone number input) to `ltr`?

**Comment by pasqualevitiello** [comment]
Fixed https://github.com/origin-space/originui/commit/4741f92f8ece4393f0f0d49f6b68a6bff12d3527

**Comment by nahasco** [comment]
> Fixed [4741f92](https://github.com/origin-space/originui/commit/4741f92f8ece4393f0f0d49f6b68a6bff12d3527)

@iftachhh might have set it to `ltr` intentionally. I see he didn't adjust the border radius and margins to support rtl when the component is in rtl.

**Comment by pasqualevitiello** [comment]
@iftachhh can you please confirm?

**Comment by iftachhh** [comment]
Hey @nahasco @pasqualevitiello , I intentionally forced the phone number input to be left-to-right as the preliminary dropdown is for the country code which will always be _left_ to the phone number, also in Arabic and Hebrew. It is in fact problematic as the direction applies also to the label and all the elements surrounding the field so I'll try later to revise it and cover it as well.

**Comment by pasqualevitiello** [comment]
Thanks for confirming @iftachhh, ltr property was just restored: https://github.com/origin-space/originui/commit/6ac4ffad99a60a14e2c8d7b52e39c8f611f6a9cc

**Pull request merged**
